<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_indexed_search"
 *
 * Auto generated by Extension Builder 2021-10-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_indexed_search'] = [
    'title' => 'Hauer-Heinrich - hh_indexed_search',
    'description' => 'Currently fixes https://forge.typo3.org/issues/95238.',
    'category' => 'distribution',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '',
            'indexed_search' => '',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\HhIndexedSearch\\' => 'Classes'
        ],
    ],
];
